# Generated by Django 5.2.1 on 2025-06-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_booking_google_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='message',
        ),
        migrations.AlterField(
            model_name='booking',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
